# Generated by Django 4.0.2 on 2022-04-05 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CellObj',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dirname', models.CharField(max_length=50)),
                ('model_cho', models.IntegerField(default=20)),
                ('gp_cho', models.CharField(max_length=20)),
                ('autosave', models.BooleanField(default=False)),
                ('c_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-c_time'],
            },
        ),
    ]
