# Generated by Django 3.1.2 on 2021-11-30 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cellForeGround', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runmodel',
            name='c_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
