# Generated by Django 3.1.2 on 2021-11-30 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cellForeGround', '0002_auto_20211130_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='runmodel',
            name='set_autosave',
            field=models.BooleanField(default=False),
        ),
    ]
