# Generated by Django 3.1.2 on 2022-04-05 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cellForeGround', '0003_runmodel_set_autosave'),
    ]

    operations = [
        migrations.CreateModel(
            name='CellObj',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dirname', models.CharField(max_length=50)),
                ('model_cho', models.IntegerField(default=20)),
                ('gp_cho', models.CharField(max_length=20)),
                ('autosave', models.BooleanField(default=False)),
                ('c_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-c_time'],
            },
        ),
        migrations.DeleteModel(
            name='RunModel',
        ),
    ]
